### PR TITLE
dev-qt/qtwebkit: Patch compiling '5.9.*' against ICU >59.

### PR DESCRIPTION
**Pull request by Chiitoo**
Upstream bug: https://bugreports.qt.io/browse/QTBUG-60532

I imagine this might get fixed upstream sooner, rather than later, but I figured I'd still offer.  :]

Test compiled 5.9.9999 and 5.9.0_beta3.

### CODE REVIEW

**Comment by Chiitoo** [comment]
Gah.

I completely forgot to make a condition for 'if' ICU 59 or higher is installed...  I don't know if things will still build with ICU <59 with these changes applied.

I had it in my mind at some point, but apparently it disappeared on the way here...

**Comment by Chiitoo** [comment]
Made patching conditional depending upon the installed ICU version.

**Comment by Chiitoo** [comment]
Rumour has it, that the patch from https://bugs.gentoo.org/618644 which is for 5.7.1, works for at least some of '5.9.*' as well, though I haven't personally tried other than applying for 5.9.9999.

It's somewhat different, but I can't tell if either one is better than the other.

**Comment by Dessa** [comment]
this landed in 5.9, 5.9.1 and dev.

**Comment by Chiitoo** [comment]
Indeed, thanks!

Closing.

**Pull request closed without merging**
