### PR TITLE
dev-qt/qtnetwork : Libressl support for 5.7

### PR DESCRIPTION
**Pull request by waltercool**
Dirty but working support for LibreSSL on QtNetwork 5.7.

### CODE REVIEW

**Comment by Pesa** [comment]
I would be inclined to reject this, see discussion in https://bugs.gentoo.org/show_bug.cgi?id=562050

@kensington are you still of the same opinion?

**Comment by waltercool** [comment]
@Pesa This patch is just intended for 5.7, not for 5.9999 or 5.7.9999 because the same reason is explained in Gentoo bugzilla, QtNetworking changes with each version, and the patch needs to be different each time. I been doing a specific patch in my local overlay for 5.5, 5.6 and now for 5.7.

Until now I haven't seen any problem with QtWebBrowser, KDE Frameworks, or other KDE Application.

**Comment by kensington** [comment]
> I would be inclined to reject this, see discussion in https://bugs.gentoo.org/show_bug.cgi?id=562050
> 
> @kensington are you still of the same opinion?

Yep, upstream's position is reasonable and I don't think we should hack around that.

**Comment by Pesa** [comment]
Closing then.

**Comment by Pesa** [comment]
> QtNetworking changes with each version, and the patch needs to be different each time. I been doing a specific patch in my local overlay for 5.5, 5.6 and now for 5.7.

I'm aware of that, and it's yet another reason why we (I) don't want to carry a downstream patch.

Moreover this is very very delicate crypto stuff... I don't want to be the next distro maintainer who introduced a security bug into a package because he patched some code he didn't fully understand. Sorry.

**Pull request closed without merging**
