### PR TITLE
profiles: Unmask Qt 5.11.0 to prevent downgrades

### PR DESCRIPTION
**Pull request by johu**
Downgrading caused through 169e78e10517c0977c261cdfa90f3f59009edc7e.

### CODE REVIEW

**Comment by johu** [comment]
@Pesa @a17r  please push for me, can't write to qt overlay at the moment?!

**Comment by a17r** [comment]
I can only push to gentoo.org qt.git, not to github

**Comment by Pesa** [comment]
@a17r why can't you push to github? you did yesterday...

**Comment by Pesa** [comment]
uhm that's annoying, how can we fix it? Also, it's time you add yourself to the @gentoo/qt project ;)

**Comment by Chiitoo** [comment]
> Also, it's time you add yourself to the @gentoo/qt project ;)

Last time I said that... it wasn't pretty.

**Pull request closed without merging**
