### PR TITLE
x11-misc/sddm: Add inital support for qt6

### PR DESCRIPTION
**Pull request by FireBurn**
This gets the Plasma 6 themes working for me

### CODE REVIEW

**Comment by FireBurn** [comment]
Am I missing something to get this looked at?

**Comment by a17r** [comment]
Things just changed a bit: https://github.com/sddm/sddm/commit/27cae1af065c80f23afa28c39db6b46544ca4b5c

Also watching: https://github.com/sddm/sddm/pull/1790

**Comment by a17r** [comment]
Had some time to test this and unfortunately `USE=qt6` just ended up with mouse cursor on black screen in current state.

**Review by a17r — APPROVED** [review]
Thanks, even though Qt6 does not work for me right now, picked with inverted IUSE logic for now (a global USE=qt6 setting should not end up breaking someone's login screen), plus some other style changes (dependency sorting, reusing QTMIN but not using QT5MIN).

**Pull request closed without merging**
