### PR TITLE
dev-qt/qtcore: Drop IUSE=old-kernel

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by heroxbd** [comment]
Is it because the configure options no longer work, or we had decided to drop support of the old kernels?

**Comment by a17r** [comment]
The oldest kernel version you can get in Portage is `4.14.315`

**Review by Chiitoo — APPROVED** [review]
Thank you!

**Review by Pesa — APPROVED** [review]

**Comment by heroxbd** [comment]
> The oldest kernel version you can get in Portage is `4.14.315`

If the kernel is managed by Gentoo, yes, we don't need `USE=old-kernel`

That said, there are cases where portage does not control the kernel, e.g. WSL1, OpenVZ, Gentoo Prefix. Users could get stuck with an old kernel.

The USE flag was introduced in https://bugs.gentoo.org/669994 and in https://github.com/gentoo/qt/pull/214 

It is still needed and being used in various Gentoo scenarios.

**Comment by a17r** [comment]
Right, but that was more than 3 years ago. Is there an overview which distributions are still shipping with older kernels than 4.14?

**Comment by heroxbd** [comment]
Andreas Sturmlechner ***@***.***> writes:

> Right, but that was more than 3 years ago. Is there an overview which
> distributions are still shipping with older kernels than 4.14?

Yes, for example, CentOS 7 with linux-3.10 (EOL mid 2026) is still in
use on many HPC sites.

**Comment by a17r** [comment]
Hm. I'm not sure we should wait *that* long but there's no hurry right now either.

**Comment by heroxbd** [comment]
Andreas Sturmlechner ***@***.***> writes:

> Hm. I'm not sure we should wait that long but there's no hurry right now either.

Got you, Andreas.  Thanks for your consideration.

**Pull request closed without merging**
