### PR TITLE
dev-qt/qtwebengine: Fix 5.6.0 build with system-nss

### PR DESCRIPTION
**Pull request by a17r**
Patches taken from upstream.

### CODE REVIEW

**Comment by Pesa** [comment]
I assume this fixes bug 577676..?

**Comment by a17r** [comment]
Yes, I just found that as well

**Comment by Pesa** [comment]
Then add it to the commit message please. And also mention that the patches come from upstream.

**Comment by a17r** [comment]
done!

**Comment by Pesa** [comment]
LGTM

**Comment by Pesa** [comment]
Thanks!

**Pull request merged**
