### PR TITLE
Qt6 WIP

### PR DESCRIPTION
**Pull request by a17r**
Since I got this, might as well share what I have so far. Builds and installs fine beside Qt5.

### CODE REVIEW

**Comment by jospezial** [comment]
Would be nice to have qt6 live ebuilds in this overlay because for qt-5.15 branch open source development has ended.

**Comment by a17r** [comment]
Well, it's not really a replacement for 5.15 branch, except if you just want to build stuff for almost no revdeps. ;) Too much of a moving target so far, so no priority to put more hours into it yet.

**Comment by jospezial** [comment]
QT upstream is removing the ability to use qmake for building. Already done in dev branch.
All dev-qt ebuilds and used eclasses have to be converted to use cmake instead.
I think qmake-utils.eclass is deprecated or obsolete if not directly inherited by other ebuilds.
Your qtbase-6.9999.ebuild does not use (inherit) qmake-utils.eclass or qt6-build.eclass ?

**Comment by Pesa** [comment]
agree with @a17r. 6.0 should have been a beta. Unless someone has a lot of spare time on their hands, I recommend waiting _at least_ for 6.1, expected in late April. 6.1 should also contain the changes to the install location of various tools to allow/simplify co-installability with Qt5.

> I think qmake-utils.eclass is deprecated or obsolete if not directly inherited by other ebuilds.

`qmake-utils` is not (and never has been) intended for building Qt itself, but for other software that uses qmake and/or other Qt tools at build time. There are no plans to deprecate it.

**Comment by binex-dsk** [comment]
any progress on implementing this yet

**Comment by binex-dsk** [comment]
@a17r this seems to work fine but shouldn't there be a `wayland` USE flag? Or just, well, a `qtwayland` ebuild for version 6?

**Comment by justxi** [comment]
I tried to use the ebuild to install Qt 6.1.1. 
To download and configure the sources I had to modify
- MY_P=qt-...
- in src_prepeare: -i qtbase/... (added "qtbase")

But now it fails with:
```
ninja: error: 'qtbase/src/platformsupport/input/CMakeFiles/InputSupport.dir/cmake_pch.hxx.gch', needed by 'qtbase/src/platformsupport/input/CMakeFiles/InputSupport.dir/InputSupport_autogen/mocs_compilation.cpp.o', missing and no known rule to make it
```

**Comment by justxi** [comment]
Enabling the use flag "evdev" or "libinput" solves this problem.

**Comment by justxi** [comment]
Some more experiences when compiling qtbase-6.1.1:

I have to set the "vulkan" use flag, otherwise I get this error message:
```
/var/tmp/portage/dev-qt/qtbase-6.1.1/work/qt-everywhere-src-6.1.1/qt3d/src/extras/defaults/qt3dwindow.cpp: In function ‘void Qt3DExtras::setupWindowSurface(QWindow*, Qt3DRender::API)’:
/var/tmp/portage/dev-qt/qtbase-6.1.1/work/qt-everywhere-src-6.1.1/qt3d/src/extras/defaults/qt3dwindow.cpp:319:17: error: ‘class QWindow’ has no member named ‘setVulkanInstance’
  319 |         window->setVulkanInstance(&Qt3DRender::staticVulkanInstance());
      |                 ^~~~~~~~~~~~~~~~~
```

According to this https://bugreports.qt.io/browse/QTBUG-68467, the following patches are necessary:
qtbase-6.1.1-qt3d-cmake-add_define_Z_OF.patch:
```
--- a/qt3d/src/3rdparty/assimp/assimp.cmake	2021-06-12 20:55:49.714021978 +0200
+++ b/qt3d/src/3rdparty/assimp/assimp.cmake	2021-06-12 20:56:02.291020988 +0200
@@ -257,6 +257,7 @@
             RAPIDJSON_HAS_STDSTRING=1
             RAPIDJSON_NOMEMBERITERATORCLASS
             ASSIMP_BUILD_NO_LIMITBONEWEIGHTS_PROCESS
+            OF=_Z_OF
         INCLUDE_DIRECTORIES
             ${assimpDir}
             ${assimpDir}/..
```

qtbase-6.1.1-qtquick3d-cmake-add_define_Z_OF.patch
```
--- a/qtquick3d/src/plugins/assetimporters/assimp/CMakeLists.txt	2021-06-12 22:06:40.234687382 +0200
+++ b/qtquick3d/src/plugins/assetimporters/assimp/CMakeLists.txt	2021-06-12 22:08:58.097676530 +0200
@@ -294,6 +294,7 @@
         RAPIDJSON_HAS_STDSTRING=1
         RAPIDJSON_NOMEMBERITERATORCLASS
         ASSIMP_BUILD_NO_LIMITBONEWEIGHTS_PROCESS
+        OF=_Z_OF
     INCLUDE_DIRECTORIES
         ../../../3rdparty/assimp
         ../../../3rdparty/assimp/..
```

Building with GCC 11 needs these patches:
qtbase-6.1.1-qt3d-add-exception_ptr.patch:
```
diff -Naur a/qt3d/src/3rdparty/assimp/src/code/Common/Importer.h b/qt3d/src/3rdparty/assimp/src/code/Common/Importer.h
--- a/qt3d/src/3rdparty/assimp/src/code/Common/Importer.h	2021-06-12 23:54:47.931176680 +0200
+++ b/qt3d/src/3rdparty/assimp/src/code/Common/Importer.h	2021-06-13 00:28:06.974019318 +0200
@@ -47,6 +47,7 @@
 #include <map>
 #include <vector>
 #include <string>
+#include <exception>
 #include <assimp/matrix4x4.h>
 
 struct aiScene;
@@ -101,7 +102,7 @@
     std::string mErrorString;
 
     /** Any exception which occurred */
-    std::exception_ptr mException;
+    std::__exception_ptr::exception_ptr mException;
 
     /** List of integer properties */
     IntPropertyMap mIntProperties;
diff -Naur a/qt3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp b/qt3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp
--- a/qt3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp	2021-06-12 23:53:48.188181383 +0200
+++ b/qt3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp	2021-06-13 00:29:01.812015001 +0200
@@ -56,6 +56,8 @@
 #error This header requires C++ to be used. Use assimp.h for plain C.
 #endif // __cplusplus
 
+#include <exception>
+
 // Public ASSIMP data structures
 #include <assimp/types.h>
 
@@ -502,7 +504,7 @@
      *
      * @note The returned value remains valid until one of the
      * following methods is called: #ReadFile(), #FreeScene(). */
-    const std::exception_ptr& GetException() const;
+    const std::__exception_ptr::exception_ptr& GetException() const;
 
     // -------------------------------------------------------------------
     /** Returns the scene loaded by the last successful call to ReadFile()
```

qtbase-6.1.1-qtquick3d-add-exception_ptr.patch:
```
diff -Naur a/qtquick3d/src/3rdparty/assimp/src/code/Common/Importer.h b/qtquick3d/src/3rdparty/assimp/src/code/Common/Importer.h
--- a/qtquick3d/src/3rdparty/assimp/src/code/Common/Importer.h	2021-06-13 07:47:47.123514227 +0200
+++ b/qtquick3d/src/3rdparty/assimp/src/code/Common/Importer.h	2021-06-13 08:16:51.855487153 +0200
@@ -47,6 +47,7 @@
 #include <map>
 #include <vector>
 #include <string>
+#include <exception>
 #include <assimp/matrix4x4.h>
 
 struct aiScene;
@@ -101,7 +102,7 @@
     std::string mErrorString;
 
     /** Any exception which occurred */
-    std::exception_ptr mException;
+    std::__exception_ptr::exception_ptr mException;
 
     /** List of integer properties */
     IntPropertyMap mIntProperties;
diff -Naur a/qtquick3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp b/qtquick3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp
--- a/qtquick3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp	2021-06-13 01:03:00.824854493 +0200
+++ b/qtquick3d/src/3rdparty/assimp/src/include/assimp/Importer.hpp	2021-06-13 08:16:29.253487504 +0200
@@ -56,6 +56,8 @@
 #error This header requires C++ to be used. Use assimp.h for plain C.
 #endif // __cplusplus
 
+#include <exception>
+
 // Public ASSIMP data structures
 #include <assimp/types.h>
 
@@ -502,7 +504,7 @@
      *
      * @note The returned value remains valid until one of the
      * following methods is called: #ReadFile(), #FreeScene(). */
-    const std::exception_ptr& GetException() const;
+    const std::__exception_ptr::exception_ptr& GetException() const;
 
     // -------------------------------------------------------------------
     /** Returns the scene loaded by the last successful call to ReadFile()
```

And I added a clang use flag which sets "QT_FEATURE_clang".

**Comment by Pesa** [comment]
>      /** Any exception which occurred */
> -    std::exception_ptr mException;
> +    std::__exception_ptr::exception_ptr mException;

This looks suspicious, where did you find this patch?

**Comment by justxi** [comment]
Of course... I didn´t found any patch... created it by myself... based on this: 
https://gcc.gnu.org/onlinedocs/gcc-11.1.0/libstdc++/api/a06147.html

**Comment by SentToDevNull** [comment]
@justxi Would you be able to upload your Qt 6.1.1 ebuild/eclass repo? I’m looking to add Qt 6.2 support, and that would serve as a great starting point.

**Comment by justxi** [comment]
@SentToDevNull You can find my updated ebuild based on the work of @a17r here: https://github.com/justxi/qt/tree/qt-6.1.1

**Comment by justxi** [comment]
@SentToDevNull Do you have support for Qt 6.2 now?

**Comment by SentToDevNull** [comment]
@justxi Almost. I modified the ebuilds so that there should be no conflicts with existing Qt5 packages. I also got `repoman` to stop complaining about most problems. The Qt project hasn't generated any tarballs for version 6.2 as of about a week or so, so I have to change all ebuilds to checkout branches related to version 6.2 for each component's individual git repo; that part is still a work in progress.

If I remember correctly, when I started, I cloned your repo but forgot to checkout the branch with your work. (Oops.) [Here](https://github.com/SentToDevNull/qt) is a link to what I've got so far. I need to take my changes from `master` and put them in a new branch (`qt-6.2.0`) and then roll in your changes from `qt-6.1.1` and do to the other packages what you did to `qtbase`. I'll probably have time later this week to do that; I'll keep you posted.

**Comment by binex-dsk** [comment]
ok i dont really know what that is in english but does that mean you'll be making Qt 6 ebuilds of other packages?

**Comment by SentToDevNull** [comment]
> does that mean you'll be making Qt 6 ebuilds of other packages?

yes, probably sometime this weekend

**Comment by justxi** [comment]
@SentToDevNull I see a lot of ebuilds in your repository. Are all working? Or What is to do?

**Comment by SentToDevNull** [comment]
@justxi Not yet. They have to be pointed to the correct git repo branches.

**Comment by justxi** [comment]
Here is a beta2 from 27th of july this year: https://download.qt.io/development_releases/qt/6.2/

According to this, the beta3 should follow at mid/end of august: https://wiki.qt.io/Qt_6.2_Release

**Comment by justxi** [comment]
@SentToDevNull Using the sources from above it is possible to add the location. Making it compile needs a lot more changes.
I first version, far from good, is in https://github.com/justxi/qt/tree/qt-6.2.0_beta2. Most changes are in the eclass file. All changes have a coment like "TODO", "Not supported?"...

**Comment by justxi** [comment]
@SentToDevNull I build Qt without ebuilds and it works simply using CMake. So I think all the ebuilds could be changed to use CMake, but I think this decision has to be made by the Gentoo developers.

**Comment by Chiitoo** [comment]
I've got

qtbase
qtdeclarative
qtmultimedia
qtshadertools
qtsvg
qttools
qtwebchannel
qtwebengine

in slot 6 installed, and ported Otter and qTox so far to test with (not exactly completely working ports yet mind you, but they build and run to some extent).

The Qt ebuilds are still very skeleton-like, however, and the eclass, as seen here, hasn't changed much, but I guess it's some sort of progress nevertheless.

**Comment by justxi** [comment]
@Chiitoo Where can I find the ebuilds?

**Comment by Chiitoo** [comment]
Nowhere public yet.

I want to put at least a little more time into the lot, though I did hope I would have done that by now.

**Comment by microcai** [comment]
any updates?
qt6 was offically released.

**Comment by a17r** [comment]
See this overlay.

**Pull request closed without merging**
