### PR TITLE
Keyword for ~arm, tested on armv6j.

### PR DESCRIPTION
**Pull request by dflogeras**
Tested on raspberry pi B, armv6j-musleabi

### CODE REVIEW

**Comment by Pesa** [comment]
Prepend `dev-qt/qtbluetooth: ` to the commit message please

**Comment by dflogeras** [comment]
What is the best way to do this?  Delete merge request, rebase, and re-request merge?  Sorry for that, I should have known.

**Comment by kensington** [comment]
I believe you can just force-push your updated commit.

**Comment by Pesa** [comment]
Rebased and merged, thanks!

**Pull request closed without merging**
