### PR TITLE
Small updates to x11-misc/sddm

### PR DESCRIPTION
**Pull request by FireBurn**
One patch was failing and isn't required any more (it tests for debian now)

The other one was just rebasing the patches, adding some headers for git am to play nicely, I've attributed the work to the committer, let me know if that's incorrect

### CODE REVIEW

**Review by a17r — CHANGES_REQUESTED** [review]
> One patch was failing and isn't required any more (it tests for debian now)

Same modification is still necessary, it just needs rebasing after being shoved into `INSTALL_PAM_CONFIGURATION` conditional in the same file.

> The other one was just rebasing the patches, adding some headers for git am to play nicely, I've attributed the work to the committer, let me know if that's incorrect

All these are versioned for a reason, they were added with 0.20 version bump and are the exact same patches. If you change them, you need to change patch file names as well. In this case I would choose 9999, since upstream have not bumped SDDM_VERSION_STRING yet and we can't assume what their next release will be.

**Comment by FireBurn** [comment]
Updated

**Comment by FireBurn** [comment]
There's something up with that rebased patch:

Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Initializing...
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Starting...
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Logind interface found
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Adding new display...
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Loaded empty theme configuration
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Using VT 1
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Display server started.
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Socket server starting...
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Socket server started.
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Greeter starting...
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] Starting...
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] Authenticating...
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] authenticate: Authentication failure
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] returning.
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Error from greeter session: "Authentication failure"
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] Asked to close the session but it wasn't previously open
Jan 02 11:29:20 axion.fireburn.co.uk sddm-helper[532]: [PAM] Ended.
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Auth: sddm-helper exited with 1
Jan 02 11:29:20 axion.fireburn.co.uk sddm[527]: Greeter stopped. SDDM::Auth::HELPER_AUTH_ERROR


Dropping it and everything works fine again, I'll take another look

**Comment by FireBurn** [comment]
Sorted

**Comment by FireBurn** [comment]
Once this is acceped I'll open a new PR with the Qt6 stuff, which allows the new Plasma 6 Breeze them to load

**Comment by a17r** [comment]
Thanks. Touching all the patches was not necessary, it seems I wasn't clear enough there; the point was to be able to trace changes to patch files without even looking into the patch or comparing with ::gentoo.

But, since you've been doing the work, I kept the added patch headers, fixed attribution and original dates in a few places and kept 0.20.0 patch versioning where the substance of the patch did not change.

**Pull request closed without merging**
