### PR TITLE
[dev-qt/qtwebkit23] Enable multilib support

### PR DESCRIPTION
**Pull request by enricotagliavini**
This change add support for building multilib version of qtwebkit23. Tested with Skype (linking to libQtWebKit.so.4 32 bit version)

### CODE REVIEW

**Comment by enricotagliavini** [comment]
about qttest: I really have no clue. I never used qmake ever, it is not obvious to me at all.

**Comment by Pesa** [comment]
Squash everything into one commit and rebase (I've fixed the qttest issue in 7ffc33f76072d7c68c4ea2449a317de77d1a3f77).

Also, use `qt4_get_bindir` from `qmake-utils` for `--qmake=...`

**Comment by enricotagliavini** [comment]
Everything squashed and changed to use qt4_get_bindir

**Comment by kensington** [comment]
Thanks a lot!

**Comment by enricotagliavini** [comment]
My pleasure and thank you for the patience :)

**Pull request merged**
