### PR TITLE
qt5-build.eclass: filter-lto

### PR DESCRIPTION
**Pull request by a17r**
Bugs: https://bugs.gentoo.org/650488
Bugs: https://bugs.gentoo.org/692078
Bugs: https://bugs.gentoo.org/713850
Bugs: https://bugs.gentoo.org/908419
Bugs: https://bugs.gentoo.org/652158
Bugs: https://bugs.gentoo.org/919043

### CODE REVIEW

**Review by thesamesam — APPROVED** [review]
yes, please - i'm interested in qt6 bugs if they happen, not for qt5 (both b/c of qmake which makes asan/ubsan hard but also the support situation)

**Review by Pesa — APPROVED** [review]

**Review by ionenwks — APPROVED** [review]
Yeah, just do it.

**Comment by ionenwks** [comment]
> yes, please - i'm interested in qt6 bugs if they happen, not for qt5 (both b/c of qmake which makes asan/ubsan hard but also the support situation)

And yeah, for Qt5 I'd argue this could be left permanently (not worth it), so the bugs can probably be closed rather than just referenced.

**Review by Chiitoo — APPROVED** [review]
Thank ye!

**Pull request merged**
