### PR TITLE
dev-python/pyside: 5.12.3 EAPI-7 bump

### PR DESCRIPTION
**Pull request by leycec**
This is the last in a series of pull requests bumping PySide2 & Friends to the "recently" <sup>*wink, wink*</sup> released first stable version of PySide2: [**PySide2 5.12.3**](https://blog.qt.io/blog/2018/12/18/qt-python-5-12-released).

This PR bumps both **`pyside:2`** and **`pyside-tools:2`** – the 500 lb. boa constrictors in the room. Since both require `shiboken:2`, this PR naturally requires [the first PR in this series](https://github.com/gentoo/qt/pull/194). Since that PR has yet to be accepted, this PR is currently just for show. Such is life for the stalwart Gentooer.

*Let's do this yet again!* :boom:

## So, What Exactly Did You Do?

Alotta stuff. The PySide2 codebase has improved more than a little since we authored these ebuilds an ageless aeon ago. Rather than exhaustively enumerate each exhausting detail, here are the highlights:

* **Renamed the `declarative` USE flag to `qml`.** This might be the most contentious change, so it gets top billing. Justifications for this modest change include:
  * **Consistency.** By renaming `declarative` to `qml`, we're then able to trivially forward this flag to all dependencies also declaring this flag (e.g., `charts? ( >=dev-qt/qtcharts-${PV}:5[qml?] )` in `${RDEPEND}`). This improves packaging consistency and system integrity for end users.
  * **Orthogonality.** At least 18 Portage packages prefer `qml` to `declarative`. Only 3 packages still use `declarative` (i.e., `PyQt5`, `designer`, and `qt-docs`), probably for legacy reasons.
  * **Disambiguity.** Since [Qt 5 deprecated the `QtDeclarative` module](https://doc.qt.io/qt-5/qtquick-porting-qt5.html#c-code), the `declarative` USE flag is arguably ambiguous and no longer descriptive. Of course, QML *is* a declarative language. But so are CSS, HTML, SQL, XML, and Lisp. `</shrug>`
* **Declared a new `quick` USE flag.** This might be the next most contentious change, so it also gets top billing. Previously, the `declarative` USE flag encompassed both QML *and* Qt Quick. While related, these two technologies are distinct – much moreso than, say, the nearly identical `script` and `scripttools` USE flags. QML is the language; Qt Quick is only one of several toolkits targeting that language. Other competing toolkits targeting QML include [The Qt Company's Qt Build System (QBS)](https://doc.qt.io/qbs), [Sailfish Silica](https://sailfishos.org/develop/docs/silica), and [BlackBerry Cascades](http://developer.blackberry.com/native/documentation/dev/fundamentals/#). Hence, there are valid USE cases (*see what I did there*) for enabling `qml` but *not* `quick`. While separating these two technologies makes intuitive sense to me, I'm a mostly reasonable man.<sup>*← bald-faced lies*</sup> I ain't got no horse in this race. If you'd rather I revert this change by folding `quick` back into `qml`, just say the magic words: "Do this or I will break you."
* **Added a countably infinite number of new USE flags and conditional dependencies.** I can't count to infinity, so I'll only list the most critical new USE flags:
  * `3d`, supporting the `Qt3D*` family of modules (e.g., `Qt3DCore`, `Qt3DAnimation`). The name `3d` derives from the `qt-docs` ebuild, which groups these modules similarly. Splitting these modules into individual USE flags would, of course, be trivial... but possibly pointless.
  * `location`, `positioning`, `sensors`, and `speech`, supporting the `QtLocation`, `QtPositioning`, `QtSensors`, and `QtTextToSpeech` modules. These names all derive from the `PyQt5` ebuild.
  * `scxml`, supporting the `QtScxml` module. This name derives from the `qt-creator` ebuild.
  * `xml`, supporting the `QtXml` module. Previously, PySide2 required `QtXml` as a core mandatory dependency. Now, it doesn't. That's nice.
* **Laboriously rewrote `${REQUIRED_USE}`.** Thank the Nordic Gods <sup>*Freya. Always Freya.*</sup> for whoever preserved the one-liner from which `${REQUIRED_USE}` was originally generated. It actually still works! Using that one-liner, I was able to reconstruct `${REQUIRED_USE}` from scratch. It was not fun, but it was done.
* **Made `QtWebEngineWidgets` dependent upon the `webengine` and `widgets` USE flags.** This brings our usage of the `QtWebEngineWidgets` module in line with our usage of the `QtMultimediaWidgets` and `QtQuickWidgets` modules, which share similar dependencies.
* **Made unit tests dependent upon `xvfb-run`.** Technically, this is an optional dependency. Pragmatically, this is effectively mandatory. Running unit tests *without* `xvfb-run` bombards the screen with egregious pop-up windows ala 1998-era Netscape Navigator. (It's not pretty.)
* **Dropped `webkit` support.** Since upstream deprecated the `QtWebKit*` family of modules in favour of `QtWebEngine*`, it hardly seems worth supporting both in PySide2. Out with the old and unsupported!
* **Dropped Python 3.4 support** *and* **added Python 3.7 support.** So it goes.
* **Dropped Gentoo Prefix support.** Out with the untested!
* **Bumped to EAPI-7.** Just 'cause.

## What Could Possibly Go Wrong?

This changeset comes bundled with two minor caveats:

* **`QtRemoteObjects`.** Technically, PySide2 supports [the recently introduced `QtRemoteObjects` module dubbed "QtRO"](https://doc.qt.io/qt-5/qtremoteobjects-index.html). This is mildly exciting, as QtRO is the sanest remote procedure call (RPC) implementation I've encountered. Admittedly, all of the other implementations I've encountered were fundamentally insane. <sup>Die, COM! Die!</sup> Sadly, we don't support this module yet. Once *someone else* contributes a working `dev-qt/qtremoteobjects` package, we'll want to revisit this ebuild and add support for a new `remoteobjects` USE flag. Until then, I shrug.
* **Apidoc generation.** Technically, PySide2 also supports generation of API documentation (i.e., "apidoc"). Sadly, we don't – mostly because I'm lazy and decrepit and prefer the original C++-oriented documentation. Once *someone else* feels like supporting this, we'll want to revisit this ebuild and add support for a new `doc` USE flag. Note that this requires the entire Qt source tree, sphinx, and Graphviz. If this had been somewhat easier, I might have done it already. Again, I shrug.

## That's Hardly Anything, Though!

Right? But that's just how we roll.

~~If you thought this was great, get ready the grand finale in the riveting saga that keeps delivering: yes, **`pyside-tools-5.12.3`.** You will be excited.~~ Actually, `pyside-tools-5.12.3` support was trivial. So, I just folded that into a separate commit of this PR. Thus concludes this epic tale of woe and regret. :popcorn:

### CODE REVIEW

**Comment by leycec** [comment]
[Mostly ignorable build failure](https://travis-ci.org/gentoo/qt/builds/557629129?utm_source=github_status&utm_medium=notification), as #194 has yet to be merged. `ヽ༼ ಠ益ಠ ༽ﾉ`

**Comment by leycec** [comment]
Thanks to @Pesa's [incisive code review](https://github.com/gentoo/qt/pull/194#pullrequestreview-261410974) and [subsequent merger notes](https://github.com/gentoo/qt/pull/194#issuecomment-511139752) at #194, this PR clearly needs a bit more time baking in the oven. Let's revisit this in a few days *after* I patch this up to comply with [the recent trilogy of `shiboken` commits](https://github.com/gentoo/qt/commit/797554b39dce8fdec55d6094445afd1144996c44).

**Comment by leycec** [comment]
**Urk!** Something has gone catastrophically wrong with the bump from 5.12.3 to 5.12.4 – *and I have no idea what that thing is*:

```
[194/1326] cd /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtCore && /usr/bin/cmake -E env LD_LIBRARY_PATH=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/libpyside:/usr/lib64 /usr/bin/python2.7 /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py QtCore --sys-path /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7 /usr/lib64/python2.7/site-packages/shiboken2
FAILED: PySide2/QtCore/CMakeFiles/QtCore_pyi 
cd /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtCore && /usr/bin/cmake -E env LD_LIBRARY_PATH=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/libpyside:/usr/lib64 /usr/bin/python2.7 /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py QtCore --sys-path /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7 /usr/lib64/python2.7/site-packages/shiboken2
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 290, in <module>
    generate_all_pyi(outpath, options=options)
  File "/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 269, in generate_all_pyi
    generate_pyi(import_name, outpath, options)
  File "/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtCore/../support/generate_pyi.py", line 190, in generate_pyi
    top = __import__(import_name)
ImportError: /usr/lib64/libshiboken2-python3.6.so.5.12: undefined symbol: _Py_FalseStruct
[195/1326] cd /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtNetwork && /usr/bin/shiboken2 --generator-set=shiboken --enable-parent-ctor-heuristic --enable-pyside-extensions --enable-return-value-heuristic --use-isnull-as-nb_nonzero /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtNetwork_global.h --include-paths=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2:/usr/include/qt5/ --typesystem-paths=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2:/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2:/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtNetwork --output-directory=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtNetwork --license-file=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtNetwork/../licensecomment.txt /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtNetwork/typesystem_network.xml --api-version=5.12 --drop-type-entries="QSctpServer;QSctpSocket"
qt.shiboken: (network) CLANG builtins includes directory: /usr/lib/clang/7.1.0/include
(network) clang_parseTranslationUnit2(0x0, cmd[7]=-isystem/usr/lib/clang/7.1.0/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2 -I/usr/include/qt5 /var/tmp/portage/dev-python/pyside-5.12.4/temp/QtNetwork_global_pDLzfV.hpp)
(network) Clang: 1 diagnostic messages:
  /usr/include/qt5/QtNetwork/qtnetwork-config.h:4:9: warning: 'QT_LINKED_OPENSSL' macro redefined
   /var/tmp/portage/dev-python/pyside-5.12.4/temp/QtNetwork_global_pDLzfV.hpp:1:10: note: in file included from /var/tmp/portage/dev-python/pyside-5.12.4/temp/QtNetwork_global_pDLzfV.hpp:1:
   /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtNetwork_global.h:60:10: note: in file included from /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtNetwork_global.h:60:
   /usr/include/qt5/QtNetwork/QtNetwork:4:10: note: in file included from /usr/include/qt5/QtNetwork/QtNetwork:4:
   /usr/include/qt5/QtNetwork/qtnetworkglobal.h:44:10: note: in file included from /usr/include/qt5/QtNetwork/qtnetworkglobal.h:44:
   /usr/include/qt5/Gentoo/gentoo-qconfig.h:7:9: note: previous definition is here


(network) [3108ms] Generating class model (681)...                             [WARNING]
(network) [3115ms] Generating enum model (5)...                                [OK]
(network) [3115ms] Generating namespace model (66)...                          [OK]
(network) [3118ms] Resolving typedefs (139)...                                 [OK]
(network) [3473ms] Fixing class inheritance...                                 [OK]
(network) [3475ms] Detecting inconsistencies in class model...                 [OK]
(network) [3679ms] Detecting inconsistencies in typesystem (3852)...           [OK]
(network) [3718ms] Checking inconsistencies in function modifications...       [OK]
(network) [3718ms] Writing log files...                                        [OK]
(network) [3738ms] Running Source generator...                                 qt.shiboken: (network) There's no user provided way (conversion rule, argument removal, custom code, etc) to handle the primitive type 'bool *' of argument 1 in function 'QHostAddress::toIPv4Address(bool * ok) const'.
[WARNING]
(network) [3966ms] Running Header generator...                                 [OK]
Done, (network) 3982ms, 2 warnings (523 known issues)
[196/1326] cd /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtTest && /usr/bin/shiboken2 --generator-set=shiboken --enable-parent-ctor-heuristic --enable-pyside-extensions --enable-return-value-heuristic --use-isnull-as-nb_nonzero /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtTest_global.h --include-paths=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2:/usr/include/qt5/ --typesystem-paths=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2:/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2:/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtTest --output-directory=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/PySide2/QtTest --license-file=/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtTest/../licensecomment.txt /var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2/QtTest/typesystem_test.xml --api-version=5.12 --drop-type-entries=""
qt.shiboken: (test) CLANG builtins includes directory: /usr/lib/clang/7.1.0/include
(test) clang_parseTranslationUnit2(0x0, cmd[7]=-isystem/usr/lib/clang/7.1.0/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2/PySide2 -I/usr/include/qt5 /var/tmp/portage/dev-python/pyside-5.12.4/temp/QtTest_global_gFZWbX.hpp)
(test) [3082ms] Generating class model (709)...                             [OK]
(test) [3091ms] Generating enum model (4)...                                [OK]
(test) [3096ms] Generating namespace model (82)...                          [OK]
(test) [3099ms] Resolving typedefs (147)...                                 [OK]
(test) [3936ms] Fixing class inheritance...                                 [OK]
(test) [3940ms] Detecting inconsistencies in class model...                 [OK]
(test) [4133ms] Detecting inconsistencies in typesystem (4816)...           [OK]
(test) [4194ms] Checking inconsistencies in function modifications...       [OK]
(test) [4195ms] Writing log files...                                        [OK]
(test) [4217ms] Running Source generator...                                 [OK]
(test) [4272ms] Running Header generator...                                 [OK]
Done, (test) 4276ms (565 known issues)
ninja: build stopped: subcommand failed.
 [31;01m*[0m ERROR: dev-python/pyside-5.12.4::qt failed (compile phase):
 [31;01m*[0m   ninja -v -j3 -l1.95 failed
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line  124:  Called src_compile
 [31;01m*[0m   environment, line 3461:  Called python_foreach_impl 'cmake-utils_src_compile'
 [31;01m*[0m   environment, line 2933:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'cmake-utils_src_compile'
 [31;01m*[0m   environment, line 2238:  Called _multibuild_run '_python_multibuild_wrapper' 'cmake-utils_src_compile'
 [31;01m*[0m   environment, line 2236:  Called _python_multibuild_wrapper 'cmake-utils_src_compile'
 [31;01m*[0m   environment, line  967:  Called cmake-utils_src_compile
 [31;01m*[0m   environment, line 1184:  Called cmake-utils_src_make
 [31;01m*[0m   environment, line 1365:  Called _cmake_ninja_src_make
 [31;01m*[0m   environment, line  708:  Called eninja
 [31;01m*[0m   environment, line 1664:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       "$@" || die "${nonfatal_args[@]}" "${*} failed"
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=dev-python/pyside-5.12.4::qt'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=dev-python/pyside-5.12.4::qt'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/dev-python/pyside-5.12.4/temp/build.log.gz'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/dev-python/pyside-5.12.4/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7'
 [31;01m*[0m S: '/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2'
```

The `"ImportError: /usr/lib64/libshiboken2-python3.6.so.5.12: undefined symbol: _Py_FalseStruct"` exception message is the telltale culprit. The Python 2.7-specific version of shiboken2 5.12.4 is forcing the Python 2.7-specific version of PySide2 5.12.4 to link against Python 3.6, which is bad.

`pkgconfig` is probably to blame. `pkgconfig` is *always* to blame. This may take longer than expected to fully sort out. <sup>*shakingmyhead*</sup>

**Comment by leycec** [comment]
**I'm in over my head.** I've tracked down the culprit to the following incorrect build logic in `/var/tmp/portage/dev-python/pyside-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/pyside2-python2_7/build.ninja`:

```
#############################################
# Link the shared library libpyside/libpyside2-python2.7.so.5.12.4

build libpyside/libpyside2-python2.7.so.5.12.4: CXX_SHARED_LIBRARY_LINKER__pyside2 libpyside/CMakeFiles/pyside2.dir/dynamicqmetaobject.cpp.o libpyside/CMakeFiles/pyside2.dir/destroylistener.cpp.o libpyside/CMakeFiles/pyside2.dir/signalmanager.cpp.o libpyside/CMakeFiles/pyside2.dir/globalreceiverv2.cpp.o libpyside/CMakeFiles/pyside2.dir/pysideclassinfo.cpp.o libpyside/CMakeFiles/pyside2.dir/pysidemetafunction.cpp.o libpyside/CMakeFiles/pyside2.dir/pysidesignal.cpp.o libpyside/CMakeFiles/pyside2.dir/pysideslot.cpp.o libpyside/CMakeFiles/pyside2.dir/pysideproperty.cpp.o libpyside/CMakeFiles/pyside2.dir/pysideqflags.cpp.o libpyside/CMakeFiles/pyside2.dir/pysideweakref.cpp.o libpyside/CMakeFiles/pyside2.dir/pyside.cpp.o libpyside/CMakeFiles/pyside2.dir/moc_destroylistener.cpp.o | /usr/lib64/libshiboken2-python3.6.so.5.12.4 /usr/lib64/libQt5Core.so.5.12.3
  LANGUAGE_COMPILE_FLAGS = -march=native -O2 -pipe -Wall -fvisibility=hidden -Wno-strict-aliasing -D QT_NO_CAST_FROM_ASCII -D QT_NO_CAST_TO_ASCII
  LINK_FLAGS = -Wl,-O1 -Wl,--as-needed
  LINK_LIBRARIES = /usr/lib64/libshiboken2-python3.6.so.5.12.4 /usr/lib64/libQt5Core.so.5.12.3
```

Clearly, `LINK_LIBRARIES` is wrong. Clearly, I have no idea who or what is generating `LINK_LIBRARIES`. Heck, I barely even know what `ninja` is.

At times like this, I wish GitHub had feudal Japanese emoji. I'd settle for a throwing star.

**Comment by Pesa** [comment]
does reverting the `cp` on line 101 of `shiboken-5.12.4.ebuild` back to an `mv` change anything?

**Comment by leycec** [comment]
Sadly... no. That's a clever idea, though. That was my first guess, too.

The *true* culprit appears to be `/usr/lib64/cmake/Shiboken2-5.12.4/Shiboken2Targets-gentoo.cmake`. I don't recall seeing that file under Shiboken2 5.12.3, but here it is nonetheless:

```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Gentoo".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "Shiboken2::libshiboken" for configuration "Gentoo"
set_property(TARGET Shiboken2::libshiboken APPEND PROPERTY IMPORTED_CONFIGURATIONS GENTOO)
set_target_properties(Shiboken2::libshiboken PROPERTIES
  IMPORTED_LOCATION_GENTOO "/usr/lib64/libshiboken2-python3.6.so.5.12.4"
  IMPORTED_SONAME_GENTOO "libshiboken2-python3.6.so.5.12"
  )

list(APPEND _IMPORT_CHECK_TARGETS Shiboken2::libshiboken )
list(APPEND _IMPORT_CHECK_FILES_FOR_Shiboken2::libshiboken "/usr/lib64/libshiboken2-python3.6.so.5.12.4" )
```

**That's insane.** For unknown reasons, Shiboken2 5.12.4 now generates a Linux distribution-specific cmake file hard-coding a single Python version. We'll probably need to patch this away... *somehow.*

I shake my skinny fist like an antennae in The Qt Company's general direction.

**Comment by leycec** [comment]
**Ugh.** `cmake` **+** `ninja` is inscrutable. I can see that `/var/tmp/portage/dev-python/shiboken-5.12.4/work/pyside-setup-everywhere-src-5.12.4/sources/shiboken2-python2_7/libshiboken/cmake_install.cmake` installs the buggy `Shiboken2Targets-gentoo.cmake` file, but I have no idea how `libshiboken/cmake_install.cmake` *itself* is generated.

About all I can discern is that  `sources/shiboken2/libshiboken/CMakeLists.txt` magically generates `sources/shiboken2-python2_7/libshiboken/cmake_install.cmake`, which magically generates `/usr/lib64/cmake/Shiboken2-5.12.4/Shiboken2Targets-gentoo.cmake`.

It's all too magical. I feel uneasy about trying to patch magical dragons I fundamentally know nothing about. Let's try locally reverting to Shiboken2 5.12.3 and see what `/usr/lib64/cmake/Shiboken2-5.12.3/Shiboken2Targets*.cmake` looked like back then.

I've exhausted myself, so this'll have to wait for a brighter day (i.e., tomorrow).

**Comment by leycec** [comment]
I couldn't help myself. Despite exhaustion, true men of the north must soldier on.

The only discernable difference between `/usr/lib64/cmake/Shiboken-5.12.3/` and `/usr/lib64/cmake/Shiboken-5.12.4/` are the contents of the `Shiboken2Config-python2.7.cmake` and `Shiboken2Config-python3.6.cmake` files. Specifically:

```
# In "/usr/lib64/cmake/Shiboken-5.12.3/Shiboken2Config-python2.7.cmake":
set(SHIBOKEN_BUILD_TYPE "Release")

# In "/usr/lib64/cmake/Shiboken-5.12.4/Shiboken2Config-python2.7.cmake":
set(SHIBOKEN_BUILD_TYPE "Gentoo")
```

**That's it.** So, Shiboken2 5.12.3 contained a bug that incorrectly set the build type to `Release`. Shiboken2 5.12.4 resolved this bug by preserving the caller-specified build type – in our case, `Gentoo`.

Ordinarily, that would be a good thing. However, by preserving the caller-specified build type, Shiboken 5.12.4 applies the `Shiboken2Targets-gentoo.cmake` file forcing use of a single hard-coded Python version. This never happens under Shiboken 5.12.3, which *also* contains the exact same `Shiboken2Targets-gentoo.cmake` file but never actually applies this file due to its incorrect setting of the build type.

The general solution is probably to muck around with the build type under Shiboken 5.12.4 to force the Shiboken 5.12.3-style behaviour of ignoring the `Shiboken2Targets-gentoo.cmake` file. Or, perhaps we can simply remove that file and everything will magically be O.K. again. *A man can hope.*

Now, we slumber. :sleeping_bed:

**Comment by leycec** [comment]
I've seen bugs you people wouldn't believe. Cmake targets on fire off the shoulder of `/usr/lib64/`. I watched Qt properties glitter in the dark near the Shiboken Gate. All those moments will be lost in time, like tears in rain. Time to commit.

**Comment by leycec** [comment]
The [Qt Bug Report to End All Qt Bug Reports](https://bugreports.qt.io/browse/PYSIDE-1053?filter=-2) has been submitted. Look forward to yet another Shiboken2 pull request that nobody asked for on Monday (in this case, resolving the above bug on our end).

This is how the Qt for Python party ends – not with a bang, but with me whimpering in the corner *as I stuff candied jellies into my vacant eye sockets.* :grimacing: :candy:

**Comment by Pesa** [comment]
I fear they might just say that parallel installations for multiple python versions are unsupported.

**Comment by leycec** [comment]
They're only human! In other words, they definitely might say that.

On the one hand, it's not a catastrophic loss if they resist adopting our low-effort recommendations. I'm reluctantly prepared to maintain Gentoo-specific PySide2 patches in perpetuity. Of course, our time is better spent elsewhere. I won't sink *much* more time interfacing with upstream, but the potential gains of doing so justify at least a few bug sporadic reports.

On the other hand, Python 2.7 *is* [officially supported until January 1st, 2020](https://pythonclock.org). The only sane means of building Shiboken2 against Python 2.7 under modern Linux distributions (most of which mandate the most recent Python 3 release as the default Python interpreter) is to override `${PYTHON_CONFIG_SUFFIX}` from the command line, which their `CMakeLists.txt` pretends to explicitly support. Preserving a caller-settable variable in a blatantly broken state would be nonsensical. If they're not going to bother properly supporting it, hopefully they simply remove it.

[On the gripping hand](http://catb.org/jargon/html/O/on-the-gripping-hand.html)... well, they're only human. All bets of rational, predictable behaviour are off the table.

**Comment by leycec** [comment]
**Boom.** #197 now resolves this specific blocker. For sanity, I've split that off into [a separate bite-sized PR](https://github.com/gentoo/qt/pull/197).

**Comment by leycec** [comment]
Last-minute improvements for the good of all, including:

* **Dropped `~x86` on both PySide2 and pyside2-tools,** for orthogonality with Shiboken2.
* **Dropped support for the deprecated `dev-qt/qtopengl` package,** because deprecated is bad. Since Qt already provides well-maintained OpenGL support via the `egl` and `gles2` USE flags on the `dev-qt/qtgui` package, `qtopengl` seems more-or-less redundant in 2019. This means that `pyside2` now only supports one deprecated package: `dev-qt/qtxmlpatterns`, for which there exists no reasonable substitute within the Qt ecosystem.
* **Renamed the `opengl` USE flag to `gles2`.** This was done for similar reasons as renaming the `declarative` USE flag to `qml`, including:
  * **Disambiguity.** After dropping `dev-qt/qtopengl`, the only OpenGL support remaining in PySide2 is GLES 2.0-specific. `</shrug>`
  * **Consistency.** By renaming `opengl` to `gles2`, we're then able to trivially forward this flag to all dependencies also declaring this flag (e.g., `gui? ( >=dev-qt/qtgui-${QT_PV}[gles2?] )` ) in `${RDEPEND}`).

Of course, there *is* one minor caveat with respect to `gles2`: PySide2 doesn't actually provide any means of disabling GLES 2.0 support. The `PySide2/QtGui/CMakeLists.txt` and `PySide2/QtOpenGLFunctions/CMakeLists.txt` makefiles test for GLES 2.0 support by testing whether the `Qt5::Gui` cmake property defined by `/usr/lib64/cmake/Qt5Gui/Qt5GuiConfig.cmake` at `dev-qt/qtgui` installation time contains the substring `opengles2`. Since cmake properties cannot be overridden by CLI options, these makefiles must instead be conditionally patched to avoid these tests.

Thanks to the virtue of laziness, I have yet to do that. Desktop profiles hard-mask the `gles2` USE flag anyway, so it's unclear whether anyone actually cares about this. If someone *does* actually care about, perhaps we can resolve this with a subsequent PR. Ideally, an issue should also be filed with upstream requesting a CLI-settable cmake variable to control this.

*Upstream. Always upstream.*

**Comment by leycec** [comment]
*Darn you, Travis-CI!* [`repoman` hates the `gles2` USE flag](https://travis-ci.org/gentoo/qt/builds/562890818?utm_source=github_status&utm_medium=notification), presumably due to hard-masks under desktop profiles. I can only collectively shrug.

I probably shouldn't even go there, but... why *is* `gles2` hard-masked under desktop profiles, anyway? Doesn't Wayland's Weston compositor effectively require `gles2` under both desktop and embedded systems (e.g., for Direct Rendering Management (DRM), which probably everyone wants)?

On second thought, let's just forget I asked.

**Comment by leycec** [comment]
Unless I'm manhandled by any *other* last-minute insights in the bathtub, both this and #197 should now be good to go for that gut-wrenching code review. :dagger: 

The Eagle is landing, folks.

**Comment by Chiitoo** [comment]
> I probably shouldn't even go there, but... why _is_ `gles2` hard-masked under desktop profiles, anyway? Doesn't Wayland's Weston compositor effectively require `gles2` under both desktop and embedded systems (e.g., for Direct Rendering Management (DRM), which probably everyone wants)?

Bug 627758 [1] might be worth a peek.

> On second thought, let's just forget I asked.

Too late!  :]

1. https://bugs.gentoo.org/627758

**Comment by leycec** [comment]
@Chiitoo, the wandering masterless [浪人](https://www.youtube.com/watch?v=KiCWrDMZZFk) that this thread deserves.

> profiles: desktop: Mask USE=gles2 in relevant packages
> Users too often burn themselves when enabling this flag globally.

[This saddens me.](https://bugs.gentoo.org/627758#c4) Yet, I sympathize. Masking one problematic USE flag for the betterment of userland is always the right decision.

When developer resources permit,<sup>so, never</sup> it might be useful to standardize any remaining discrepancies between the `opengl`, `egl*`, and `gles*` family of USE flags. Of course, the realist in me accepts that this train left the station and derailed itself on the bitter shoals of reality years ago. Now, I can only pray for Qt **+** Vulkan to save us from ourselves.

**Comment by leycec** [comment]
See also: [this closing comment.](https://github.com/gentoo/qt/pull/197#issuecomment-536419907)

**Pull request closed without merging**
